### ISSUE TITLE
M1 Chip issue when we generate Passcode - Twilio CLI

### ISSUE THREAD

**Issue by JigarAdbiz** [twilio/twilio-video-app-ios#185]
> #### Before Creating an Issue
>
> - If there is an issue specific to the video app report it here. If there is an issue or question related to the video SDK please [create an SDK issue](https://github.com/twilio/twilio-video-ios/issues) instead.
> - Make sure the issue is not already addressed by [docs](https://www.twilio.com/docs/video) or [existing issues](https://github.com/twilio/twilio-video-app-ios/issues).
> - Please do not share any 
[Personally Identifiable Information](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive information like API keys when creating an issue.

#### Description

/Users/adbizinterview/.twilio-cli/node_modules/p-cancelable/index.js:48
					throw new Error('The `onCancel` handler was attached after the promise settled.');
					      ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/adbizinterview/.twilio-cli/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/Users/adbizinterview/.twilio-cli/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/adbizinterview/.twilio-cli/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:640:26)
    at Request.emit (node:events:520:28)
    at Timeout.retry (/Users/adbizinterview/.twilio-cli/node_modules/got/dist/source/core/index.js:1270:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

#### Steps to Reproduce

1. [Step one]
1. [Step two]
1. [Insert as many steps as needed]

#### Expected Behavior

[What you expect to happen]

#### Versions

- Video app version: [e.g. 0.1.0 (33)]
- iOS version: [e.g. 13.1]
- Device: [e.g. iPhone 11]
- Xcode version: [e.g. 11.3.1]

#### Log
```
// Log output when the issue occurs
```

**Comment by timrozum** [comment]
Hi @JigarAdbiz have you tried these steps? https://github.com/twilio/twilio-video-app-ios#troubleshooting

Also can you explain the steps you took to encounter this error? Thanks!

**Comment by timrozum** [comment]
Going to close this out but let me know if you have more questions.
